"""New Migration

Revision ID: 2695b2c4de7b
Revises: 
Create Date: 2023-10-19 22:15:03.600187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = '2695b2c4de7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id'),
    sa.UniqueConstraint('currency')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('lightning_address', sa.String(), nullable=False),
    sa.Column('withdrawal_fee', sa.Integer(), nullable=True),
    sa.Column('preferred_fiat_currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lightning_address'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'payments',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('source_wallet_id', sa.String(), sa.ForeignKey('wallets.id', name='fk_payments_source_wallet_id'), nullable=False),
        sa.Column('receiver_wallet_id', sa.String(), sa.ForeignKey('wallets.id', name='fk_payments_receiver_wallet_id'), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('sent_payment', sa.Boolean(), default=False), 
        sa.Column('receive_payment', sa.Boolean(), default=False),
        sa.Column('fees', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=func.now()),
        sa.Column('payment_status', sa.String(), default="Pending"),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('source_wallet_id != receiver_wallet_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balances')
    op.drop_table('wallets')
    op.drop_table('assets')
    # ### end Alembic commands ###
