"""UUID field change

Revision ID: 32dd13219bff
Revises: 0eacc72c6c31
Create Date: 2023-10-17 13:25:32.144227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd13219bff'
down_revision: Union[str, None] = '0eacc72c6c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('uuid', sa.String(), nullable=False))
    op.drop_constraint('wallet_id_key', 'wallet', type_='unique')
    op.drop_column('wallet', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('wallet_id_key', 'wallet', ['id'])
    op.drop_column('wallet', 'uuid')
    # ### end Alembic commands ###
