"""wallet creation

Revision ID: 60be538e8174
Revises: d7d3b858d98a
Create Date: 2023-10-17 12:53:59.121036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60be538e8174'
down_revision: Union[str, None] = 'd7d3b858d98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('fiatBalance', sa.String(), nullable=True),
    sa.Column('btcBalance', sa.Integer(), nullable=True),
    sa.Column('lightingAddress', sa.String(), nullable=True),
    sa.Column('withdrawalFee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
