"""empty message

Revision ID: e309ec68fdeb
Revises: 32dd13219bff
Create Date: 2023-10-17 23:49:53.833787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e309ec68fdeb'
down_revision: Union[str, None] = '32dd13219bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('lightning_address', sa.String(), nullable=False),
    sa.Column('withdrawal_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('NGN', 'KES', name='currencyenum'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wallet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiatBalance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('btcBalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lightingAddress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('withdrawalFee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table('balances')
    op.drop_table('wallets')
    # ### end Alembic commands ###
